version: '3'

services:

  idempotency-curator:
    container_name: idempotency-curator
    restart: always
    build:
      context: ./idempotency-curator
    hostname: idempotency-curator
    ports:
      - 20000:20000
    networks:
      - backend

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - backend
    ports:
      - 6379:6379

networks:
  backend:
