version: '3'

services:

  idempotency-curator:
    container_name: idempotency-curator
    restart: always
    build:
      context: ./idempotency-curator
    hostname: idempotency-curator
    ports:
      - 20000:20000
    networks:
      - backend

  db-idempotency-curator:
    container_name: idempotency-curator
    restart: always
    image: postgres:12.2-alpine
    hostname: idempotency-curator
    volumes:
      - db-idempotency-curator:/var/lib/postgresql/data:delegated
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=idempotency-curator
      - POSTGRES_PASSWORD=idempotency-curator
      - POSTGRES_DB=idempotency-curator
    networks:
      - backend

networks:
  backend:
  frontend:

volumes:
  db-idempotency-curator:
